RDCC-2382: Hide internal POST APIs & Separate Controller for /users*
hmcts/rd-caseworker-ref-api pull request #167
Opened 2021-02-05 10:51 UTC by AdilOoze

### JIRA link (if applicable) ###

[RDCC-2382](https://tools.hmcts.net/jira/browse/RDCC-2382)

### Change description ###

- [x] Hide internal `POST` APIs:

1. `/refdata/case-worker/users`
2. `/refdata/case-worker/idam-roles-mapping`

- [x] Create Separate Controller for `/users*` endpoints

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-02-05 12:51 UTC, abhijitdiwan approved these changes

2021-02-05 12:57 UTC, nitishsingla1234 submitted a review, later dismissed

2021-02-05 12:58 UTC, ConorH994 submitted a review, later dismissed

2021-02-09 14:19 UTC, SujeethKumarAri commented
Sorry @AdilOoze for late review - I think you need to change this https://github.com/hmcts/rd-caseworker-ref-api/blob/master/src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/FeatureToggleServiceImpl.java#L40

to `CaseWorkerRefUsersController.createCaseWorkerProfiles` and also associated tests

2021-02-09 14:19 UTC, SujeethKumarAri requested changes
Sorry @AdilOoze for late review - I think you need to change this https://github.com/hmcts/rd-caseworker-ref-api/blob/master/src/main/java/uk/gov/hmcts/reform/cwrdapi/service/impl/FeatureToggleServiceImpl.java#L40

to `CaseWorkerRefUsersController.createCaseWorkerProfiles` and also associated tests

2021-02-12 14:51 UTC, ConorH994 submitted a review, later dismissed

2021-02-12 14:52 UTC, SujeethKumarAri submitted a review, later dismissed

2021-02-16 13:24 UTC, SujeethKumarAri approved these changes

2021-02-16 14:26 UTC, ConorH994 approved these changes

2021-02-16 15:19 UTC, merged