feat: RDCC-3540 Upload Template Improvements
hmcts/rd-caseworker-ref-api pull request #373
Opened 2021-11-12 13:03 UTC by SujeethKumarAri

### JIRA link ###
https://tools.hmcts.net/jira/browse/RDCC-3540

### Change description ###
Upload Template Improvements

- Updated sheet name from Caseworker Data to 'Staff Data' in file and code
- Changed Area of work header just to Service (e.g. Service1, Service2 etc.)
- Changed the name of User Type from CTRT to 'Future Operations'
- Added “NBC” to User Type

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-11-18 16:37 UTC, shreedhar-hmcts approved these changes

2021-11-18 16:38 UTC, ishratt approved these changes

2021-11-18 21:27 UTC, ManishParyani approved these changes

2021-11-19 09:03 UTC, ManishParyani requested changes
Do not merge

2021-11-23 10:27 UTC, ManishParyani approved these changes

2021-11-24 15:05 UTC, merged