RDCC-4669: Staff - Updates to Business Roles in Staff Template
hmcts/rd-caseworker-ref-api pull request #492
Opened 2022-05-18 15:42 UTC by ishratt

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-4669

### Change description ###
Updated business roles in staff template

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-05-19 13:32 UTC, SujeethKumarAri requested changes
Approved but blocking until the necessary template changes are done

2022-06-29 16:05 UTC, SujeethKumarAri approved these changes

2022-06-30 11:27 UTC, nayeemshaik-hmcts requested changes
Merge as part of the WA release

2022-06-30 11:27 UTC, nayeemshaik-hmcts approved these changes

2022-07-03 08:55 UTC, nayeemshaik-hmcts approved these changes

2022-07-03 09:12 UTC, merged