Fea:To handle  500 HTTP responses
hmcts/rd-caseworker-ref-api pull request #500
Opened 2022-05-24 17:13 UTC by shivajihmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDCC-4680

### Change description ###

To handle  500 HTTP responses

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-05-27 08:07 UTC, SujeethKumarAri requested changes

2022-05-27 08:07 UTC, SujeethKumarAri commented on src/main/java/uk/gov/hmcts/reform/cwrdapi/config/SecurityEndpointFilter.java
> +
You can remove these unused static variables

2022-05-27 08:07 UTC, SujeethKumarAri commented on src/main/java/uk/gov/hmcts/reform/cwrdapi/config/SecurityEndpointFilter.java
> +
You can remove these unused static variables

2022-05-27 08:07 UTC, SujeethKumarAri commented on src/main/java/uk/gov/hmcts/reform/cwrdapi/config/SecurityEndpointFilter.java
> +    IdamApi idamApi;
Can you remove this please as it is not used?

2022-05-27 08:07 UTC, SujeethKumarAri commented on src/main/java/uk/gov/hmcts/reform/cwrdapi/config/SecurityEndpointFilter.java
> +    IdamApi idamApi;
Can you remove this please as it is not used?

2022-06-07 15:07 UTC, SujeethKumarAri approved these changes

2022-06-07 15:41 UTC, AdilOoze approved these changes

2022-06-08 06:16 UTC, merged