RDCC-5182 fix for version compare in SRD file
hmcts/rd-caseworker-ref-api pull request #533
Opened 2022-08-02 16:32 UTC by nayeemshaik-hmcts

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-5182

### Change description ###
Staff Reference Data upload template - Version check

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-08-02 16:50 UTC, nayeemshaik-hmcts reviewed
Block the PR from merge.

2022-08-03 09:29 UTC, SujeethKumarAri requested changes
Blocking from accidental merge

2022-08-10 14:54 UTC, SujeethKumarAri approved these changes

2022-08-10 15:02 UTC, shivajilokare approved these changes

2022-08-19 12:45 UTC, merged