Staff : Update skill table with the new skills for PrL
hmcts/rd-caseworker-ref-api pull request #654
Opened 2023-02-02 22:20 UTC by ishratt

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RDCC-6226

### Change description ###
Updated skill table with new skills and removed old skills

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-03 12:28 UTC, shivajihmcts requested changes
Flyway changed should be in sync with dataload, Please check and add required scripts in jrd dataload

2023-02-03 12:33 UTC, ishratt commented
> Flyway changed should be in sync with dataload, Please check and add required scripts in jrd dataload

@shivajihmcts This is for caseworker only, we don't have any dataload project for this one.

2023-02-03 12:34 UTC, manukundloo-hmcts approved these changes

2023-02-03 14:40 UTC, AdilOoze approved these changes

2023-02-05 09:15 UTC, shivajihmcts approved these changes

2023-02-09 12:31 UTC, merged