DTSRD-2504: fix location issue across multiple services
hmcts/rd-caseworker-ref-api pull request #832
Opened 2024-04-02 12:30 UTC by kiran-yenigala-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-04-02 12:42 UTC, SabinaHMCTS submitted a review, later dismissed

2024-04-02 13:29 UTC, rajkatla-hmcts requested changes

2024-04-02 13:29 UTC, rajkatla-hmcts commented on src/integrationTest/resources/db/testmigration/V1_21__alter_case_worker_location.sql
> +ALTER TABLE CASE_WORKER_LOCATION ADD CONSTRAINT CASE_WORKER_LOCN_ID_UQ UNIQUE (CASE_WORKER_ID, LOCATION_ID, LOCATION);
Integration tests missing

2024-04-03 12:46 UTC, SabinaHMCTS approved these changes

2024-04-03 16:52 UTC, SabinaHMCTS approved these changes

2024-04-03 17:10 UTC, rajkatla-hmcts approved these changes

2024-04-03 17:10 UTC, merged