DTSRD-91: Update SRD (caseworker ref api) to Spring Boot 3
hmcts/rd-caseworker-ref-api pull request #919
Opened 2024-07-30 11:58 UTC by kiran-yenigala-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-09-11 08:30 UTC, lukasz-wolski submitted a review, later dismissed

2024-09-11 09:24 UTC, kiran-yenigala-hmcts commented on src/main/resources/db/migration/V1_26__alter_case_worker_error_description.sql
done

2024-09-11 09:24 UTC, kiran-yenigala-hmcts commented on src/integrationTest/resources/db/testmigration/V1_22__alter_case_worker_error_description.sql
done

2024-09-12 14:22 UTC, rajkatla-hmcts requested changes

2024-09-30 15:36 UTC, SabinaHMCTS approved these changes

2024-09-30 15:53 UTC, rajkatla-hmcts approved these changes

2024-09-30 16:12 UTC, lukasz-wolski approved these changes

2024-09-30 17:09 UTC, merged